version: "3.8"
services:
  web:
    build:
      context: .
      args:
        - DATABASE_URL=file:/config/dev.db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/config/dev.db
    volumes:
      - ./config:/config
    depends_on:
      - migration

  migration:
    build:
      context: .
      args:
        - DATABASE_URL=file:/config/dev.db
    command: npx prisma migrate deploy
    environment:
      - DATABASE_URL=file:/config/dev.db
    volumes:
      - ./config:/config
